--- 
title: "`cloud2trees` Species Validation"
author: "George Woolsey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    includes:
      in_header: header.html
documentclass: book
book_filename: "cloud2trees_species_validation"
output_dir: "../docs"
language:
  ui:
    chapter_name: "Section "
delete_merged_file: true
bibliography: [packages.bib]
biblio-style: apalike
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
suppress-bibliography: true
lang: en-US
zotero: true
link-citations: true
description: ""
---

# Introduction

The `cloud2trees` R [package](https://github.com/georgewoolsey/cloud2trees) provides a framework for generating  single-tree forest inventories from aerial point cloud data. The pipeline consolidates workflows to process raw point clouds, identify individual trees, and extract or model tree-level structural attributes including location, height, diameter at breast height (DBH), and crown base height (CBH). Because aerial point clouds lack the spectral information typically used to identify tree species natively, species-level information within the `cloud2trees` framework is currently a critical gap. To address this limitation, this analysis evaluates a novel, computationally efficient workflow designed to predict tree species by fusing point cloud structural data with the [USFS TreeMap](https://www.fs.usda.gov/rds/archive/catalog/RDS-2025-0032) data product. TreeMap is a raster map of imputed FIA plot identifiers at 30-meter spatial resolution for the conterminous United States, which can be used to link with FIA-measured tree list data. This FIA tree list data is already used in `cloud2trees` to build site-specific allometric equations to predict DBH from tree height using the trees of the TreeMap imputed plots.


## Proposed Species Classification Method

The proposed workflow will use the imputed FIA plot lists from the 30-meter TreeMap raster product that fall within the extent of the point cloud being evaluated. Because the TreeMap data product is a raster of imputed plots for a given area at 30m resolution, we should not assume that the tree list of an imputed plot represents the actual trees present at that location with complete accuracy. Instead, we expect the TreeMap imputed plots to be more accurate as we look over a broader area with accuracy decreasing at smaller scales. That is, when we consider the tree composition of an entire forest stand we expect TreeMap to generally get the main species and forest type correct but for each 30m raster cell we expect it to be less accurate within a single cell, potentially being a completely incorrect representation of the actual ground setting. As such, we’ll weight the individual tree records based on the stability of the imputed plots looking over a window surrounding the focal cell. Specifically, we’ll calculate the proportion of surrounding cells (5x5) that share the same imputed plot identifier as the focal cell and use this weight as a measure of TreeMap’s predicted stability to place less weight on plots that occur infrequently and more weight on plots that occur frequently.

To train the predictive model, trees from the selected FIA lists are assigned to their respective cell centers. Their coordinates are then spatially jittered within the 30-meter pixel boundary. This jittering breaks up the artificial grid lines of the raster data, creating a continuous spatial surface while preserving the broader species distribution trends. Using the FIA tree list data, we'll build an ensemble of Random Forest species classification models trained on tree height and spatial coordinates. Because tree species is a categorical variable, we'll generate a single prediction for each tree from the model ensemble using a majority voting system to output the final species prediction for each point cloud-derived tree.

## Validation Data and Accuracy Evaluation

To test this propsed species classification method, we compiled a collection of validation datasets across diverse forest conditions for this specific analysis project. These datasets consist of coincident aerial point cloud data (including USGS 3DEP ALS, UAS-lidar, and UAS-SfM) paired with field-measured stem maps or plot inventories where species identities are known.

We'll evaluate the species classification method using two approaches:

1. **Individual Tree-Level Accuracy**

This approach evaluates classification accuracy at the individual tree level. It maps every predicted tree species against the reference field-measured tree using a classical confusion matrix cross-tabulation. Given that our analysis is focused on evaluating the proposed taxonomic classification algorithm (rather than the individual tree detection method), we'll evaluate the taxonomic classification accuracy conditionally for successfully detected tree crowns (true positive matches). This conditional evaluation will allow us to isolate taxonomic classification performance from tree detection errors.

The confusion matrix will allow us to calculate class-specific performance metrics, including producer's accuracy (omission error) and user's accuracy (commission error) and overall accuracy.

2. **Stand-Wide Compositional Accuracy**

Instead of evaluating trees one by one, this accuracy evaluation aggregates the species counts or proportions across an entire plot or forest stand. It then calculates the Bray-Curtis dissimilarity index to compare the predicted species composition against the observed field composition. The index returns a value between 0 and 1, where 0 indicates identical species compositions and 1 indicates completely non-overlapping communities. Because Bray-Curtis is a dissimilarity measure, it can be interpreted as: 

$$\textrm{Bray-Curtis}_{dissimilarity} \approx 1-\textrm{Bray-Curtis}_{similarity}$$

The Bray-Curtis index is a widely trusted metric in [community ecology](https://vegandevs.github.io/vegan/reference/vegdist.html). Dissimilarity/similarity metrics tell us how well the proposed method captures the overall ecological community structure. Even if individual tree predictions are misaligned, the proposed method may still capture the correct stand-level abundance proportions, which can still be valuable for management.

## Benefits and Next Steps

Integrating species identification directly into the `cloud2trees` framework would enable the direct assign individual tree species before modeling secondary biophysical attributes (e.g., DBH, CrBH, CrBD) could improve tree-level precision (Weiskittel et al., 2011) and management decisions that require consideration of individual tree species for removal and retention during silvicultural treatment design or in modeling tree-level fire effects. Ultimately, these methods could enable the integration of species-specific allometries and fire behavior parameters at scale, supporting management needs where explicit tree-level species identification is less critical.

* **Species-Specific Allometry**: Attaching species to the point cloud-derived tree list enables the application of targeted allometric equations such as those currently used to predict DBH from tree height.

* **Biomass and Volume Mapping**: Attaching species to the point cloud-derived tree list allows individual tree metrics to feed directly into the National Scale Volume Biomass (NSVB) [equations](https://github.com/mbrussell/NSVB) and total tree and tree component biomass based on [existing allometries](https://github.com/ropensci/allodb). These equations require species information alongside structural dimensions to model merchantable timber volume, total aboveground biomass, and tree component (e.g. stem, crown) biomass.


```{r, include=FALSE, echo=FALSE}
knitr::write_bib(c(
  .packages(),
  "bookdown"
  , "knitr"
  , "rmarkdown"
  , "tidyverse"
  , "viridis"
  , "RColorBrewer"
  , "scales"
  , "latex2exp"
  , "mapview"
  , "kableExtra"
  , "patchwork"
  , "ggnewscale"
  , "terra"
  , "sf"
  , "cloud2trees"
), 'packages.bib')
```
